server:
  port: ${PORT:8080}
  
spring:
  application:
    name: pokemonnn-backend
  h2:
    console:
      enabled: true
  data:
    jdbc: 
      repositories:
        enabled: true
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**
